---
driver:
  name: vagrant
  
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-10
    driver:
      box: OC_Win10
    os_type: windows
    shell_type: powershell
    transport:
        name: winrm    

suites:
  - name: default
    run_list:
      - recipe[mongodb-windows::install]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
